### ISSUE TITLE
How to set Default indicator pragmatically ?

### ISSUE THREAD

**Issue by TestWts2017** [loicteillard/EasyTabs#1]
How to set Default indicator pragmatically ? I want to set unselected indicator for tab how it is possible with EasyTabs Can you please help me>?

**Comment by apocalx** [comment]
When you set the easytabs viewpager, you can add a second argument :
easyTabs.setViewPager(viewpager, 2);

2 => index of default tab

Or if you want to do this after the init, just use the classic viewpager way : viewpager.setCurrentItem(xx);

**Comment by TestWts2017** [comment]
I am asking for unselected tab indicator. when tab is select
![device-2018-01-31-132522](https://user-images.githubusercontent.com/34827645/35611165-3850bfb0-068a-11e8-9258-10f1c29cc623.png)
ed there is indicator for that. what about other.  see image I have 4 tab which has gray line
